# Generated by Django 2.2 on 2019-04-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('HC', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('jacket', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rd1StablefordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1_stbl', models.IntegerField(blank=True, null=True)),
                ('slot2_stbl', models.IntegerField(blank=True, null=True)),
                ('slot3_stbl', models.IntegerField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Rd1HoleModel')),
            ],
        ),
        migrations.CreateModel(
            name='Rd1SlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_slot', models.IntegerField(unique=True)),
                ('player_holesplayed', models.IntegerField(blank=True, null=True)),
                ('player_score', models.IntegerField(blank=True, null=True)),
                ('player_stbl', models.IntegerField(blank=True, null=True)),
                ('player_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel')),
            ],
            options={
                'ordering': ['-player_stbl'],
            },
        ),
        migrations.CreateModel(
            name='Rd1ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1_score', models.IntegerField(blank=True, null=True)),
                ('slot2_score', models.IntegerField(blank=True, null=True)),
                ('slot3_score', models.IntegerField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Rd1HoleModel')),
            ],
        ),
    ]
