# Generated by Django 2.2 on 2019-04-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_playermodel_rd1scoremodel_rd1slotmodel_rd1stablefordmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='picture',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='playerimages'),
        ),
    ]
