# Generated by Django 2.2 on 2019-04-04 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190403_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot10_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot11_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot12_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot4_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot5_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot6_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot7_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot8_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='slot9_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot10_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot11_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot12_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot4_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot5_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot6_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot7_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot8_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1stablefordmodel',
            name='slot9_stbl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd1slotmodel',
            name='player_slot',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
