# Generated by Django 2.2 on 2019-04-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190404_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rd1slotmodel',
            options={'ordering': ['-player_rankscore', 'player_name__HC']},
        ),
        migrations.AlterField(
            model_name='rd1slotmodel',
            name='player_rankscore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
