# Generated by Django 2.2 on 2019-04-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190405_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CTPModel',
            new_name='Rd1CTPModel',
        ),
    ]
