# Generated by Django 2.2 on 2019-04-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190405_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd1scoremodel',
            name='ctp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel'),
        ),
    ]
