# Generated by Django 2.2 on 2019-04-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190405_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd1scoremodel',
            name='ctp1_score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
