# Generated by Django 2.2 on 2019-04-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190405_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd1scoremodel',
            name='ctp1_score',
        ),
        migrations.AddField(
            model_name='rd1scoremodel',
            name='ctp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel'),
        ),
    ]
