# Generated by Django 2.2 on 2019-04-06 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190405_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd1holemodel',
            name='LD',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
    ]
