# Generated by Django 2.2 on 2019-04-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190405_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd1scoremodel',
            name='ld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ld', to='catalog.PlayerModel'),
        ),
        migrations.AlterField(
            model_name='rd1scoremodel',
            name='ctp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctp', to='catalog.PlayerModel'),
        ),
    ]
