# Generated by Django 2.2 on 2019-04-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_authmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthModel',
            new_name='PlayerAuthModel',
        ),
    ]
