# Generated by Django 2.2 on 2019-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190405_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerauthmodel',
            name='passwordcheck',
            field=models.CharField(blank=True, default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playerauthmodel',
            name='password',
            field=models.CharField(blank=True, default='password', max_length=30, null=True),
        ),
    ]
