# Generated by Django 2.2 on 2019-04-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190407_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerauthmodel',
            name='passwordcheck',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
