# Generated by Django 2.2 on 2019-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_playerauthmodel_passwordset'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerauthmodel',
            name='passwordauth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
