# Generated by Django 2.2 on 2019-04-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_playerauthmodel_passwordauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerauthmodel',
            name='passwordauth',
        ),
        migrations.RemoveField(
            model_name='playerauthmodel',
            name='passwordset',
        ),
        migrations.CreateModel(
            name='PlayerPasswordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordset', models.CharField(blank=True, default='password', max_length=30, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel')),
            ],
        ),
    ]
