# Generated by Django 2.2 on 2019-04-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20190407_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsTippingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip1', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerpasswordmodel',
            name='username',
        ),
        migrations.DeleteModel(
            name='PlayerAuthModel',
        ),
        migrations.DeleteModel(
            name='PlayerPasswordModel',
        ),
    ]
