# Generated by Django 2.2 on 2019-04-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20190407_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd1ctpmodel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Rd1SlotModel'),
        ),
    ]
