# Generated by Django 2.2 on 2019-04-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20190409_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd1scoremodel',
            name='ctp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctp', to='catalog.Rd1SlotModel'),
        ),
    ]
