# Generated by Django 2.2 on 2019-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_evententrymodel_leaderboardmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententrymodel',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
