# Generated by Django 2.2 on 2019-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20190409_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
