# Generated by Django 2.2 on 2019-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_playermodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
