# Generated by Django 2.2 on 2019-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_playermodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
