# Generated by Django 2.2 on 2019-04-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20190409_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermodel',
            options={'ordering': ['-total']},
        ),
    ]
