# Generated by Django 2.2 on 2019-04-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20190409_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportsTippingModel',
        ),
    ]
