# Generated by Django 2.2 on 2019-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_sportstippingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game1',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('PLAYER_1', 'Player 1'), ('PLAYER_2', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game10',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ISLANDERS', 'Islanders'), ('PENGUINS', 'Penguins')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game2',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('GIANTS', 'Giants'), ('PIRATES', 'Pirates')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game3',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('TEAM_1', 'Player 1'), ('TEAM_2', 'Player 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game4',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('TEAM_1', 'Player 1'), ('TEAM_2', 'Player 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game5',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('MAPLE_LEAFS', 'Maple Leafs'), ('BRUINS', 'Bruins')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game6',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ROYALS', 'Player 1'), ('INDIANS', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game7',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('MAN_CITY', 'Man City'), ('TOTTENHAM', 'Tottenham'), ('DRAW', 'Draw')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game8',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('WEST_HAM', 'West Ham'), ('LEICESTER_CITY', 'Leicester City'), ('DRAW', 'Draw')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game9',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('YANKEES', 'Yankees'), ('ROYALS', 'Royals')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FridaySocialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('best', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best', to='catalog.PlayerModel')),
                ('honorable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorable', to='catalog.PlayerModel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel')),
            ],
        ),
    ]
