# Generated by Django 2.2 on 2019-04-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20190410_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaysocialmodel',
            name='best',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_best', to='catalog.PlayerModel'),
        ),
        migrations.AlterField(
            model_name='fridaysocialmodel',
            name='honorable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_honorable', to='catalog.PlayerModel'),
        ),
        migrations.CreateModel(
            name='SaturdaySocialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('best', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_best', to='catalog.PlayerModel')),
                ('honorable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_honorable', to='catalog.PlayerModel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel')),
            ],
        ),
    ]
