# Generated by Django 2.2 on 2019-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20190410_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='tournum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
