# Generated by Django 2.2 on 2019-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20190411_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAgendaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, choices=[('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, null=True)),
                ('event', models.CharField(blank=True, choices=[('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, choices=[('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
