# Generated by Django 2.2 on 2019-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20190411_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragendamodel',
            name='location',
        ),
        migrations.AddField(
            model_name='touragendamodel',
            name='locations',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='touragendamodel',
            name='event',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='touragendamodel',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
