# Generated by Django 2.2 on 2019-04-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20190411_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragendamodel',
            name='locations',
        ),
        migrations.AddField(
            model_name='touragendamodel',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='touragendamodel',
            name='event',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='touragendamodel',
            name='time',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
