# Generated by Django 2.2 on 2019-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20190411_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsTippingResultsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.CharField(blank=True, choices=[('', 'Lowest score Friday'), ('PLAYER_1', 'Player 1'), ('PLAYER_2', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True)),
                ('result2', models.CharField(blank=True, choices=[('', 'Select result'), ('GIANTS', 'Giants'), ('PIRATES', 'Pirates')], max_length=10, null=True)),
                ('result3', models.CharField(blank=True, choices=[('', 'Select result'), ('PACERS', 'Pacers'), ('CELTICS', 'Celtics')], max_length=10, null=True)),
                ('result4', models.CharField(blank=True, choices=[('', 'Select results'), ('NUGGETS', 'Nuggets'), ('SPURS', 'Spurs')], max_length=10, null=True)),
                ('result5', models.CharField(blank=True, choices=[('', 'Select result'), ('MAPLE_LEAFS', 'Maple Leafs'), ('BRUINS', 'Bruins')], max_length=10, null=True)),
                ('result6', models.CharField(blank=True, choices=[('', 'Select result'), ('ROYALS', 'Player 1'), ('INDIANS', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True)),
                ('result7', models.CharField(blank=True, choices=[('', 'Select result'), ('MAN_CITY', 'Man City'), ('TOTTENHAM', 'Tottenham'), ('DRAW', 'Draw')], max_length=10, null=True)),
                ('result8', models.CharField(blank=True, choices=[('', 'Select result'), ('WEST_HAM', 'West Ham'), ('LEICESTER_CITY', 'Leicester City'), ('DRAW', 'Draw')], max_length=10, null=True)),
                ('result9', models.CharField(blank=True, choices=[('', 'Select result'), ('YANKEES', 'Yankees'), ('ROYALS', 'Royals')], max_length=10, null=True)),
                ('result10', models.CharField(blank=True, choices=[('', 'Select result'), ('ISLANDERS', 'Islanders'), ('PENGUINS', 'Penguins')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game1',
            field=models.CharField(blank=True, choices=[('', 'Lowest score Friday'), ('PLAYER_1', 'Player 1'), ('PLAYER_2', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game3',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('PACERS', 'Pacers'), ('CELTICS', 'Celtics')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game4',
            field=models.CharField(blank=True, choices=[('', 'Select results'), ('NUGGETS', 'Nuggets'), ('SPURS', 'Spurs')], max_length=10, null=True),
        ),
    ]
