# Generated by Django 2.2 on 2019-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20190412_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstippingresultsmodel',
            name='name',
            field=models.CharField(blank=True, default='result', max_length=10, null=True),
        ),
    ]
