# Generated by Django 2.2 on 2019-04-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20190412_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportstippingscoremodel',
            options={'ordering': ['-total', '-time']},
        ),
    ]
