# Generated by Django 2.2 on 2019-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20190412_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportstippingscoremodel',
            options={'ordering': ['-total', 'time']},
        ),
    ]
