# Generated by Django 2.2 on 2019-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20190412_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result1',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('PLAYER_1', 'Player 1'), ('PLAYER_2', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result10',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('ISLANDERS', 'Islanders'), ('PENGUINS', 'Penguins')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result2',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('GIANTS', 'Giants'), ('PIRATES', 'Pirates')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result3',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('PACERS', 'Pacers'), ('CELTICS', 'Celtics')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result4',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('NUGGETS', 'Nuggets'), ('SPURS', 'Spurs')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result5',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('MAPLE_LEAFS', 'Maple Leafs'), ('BRUINS', 'Bruins')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result6',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('ROYALS', 'Player 1'), ('INDIANS', 'Player 2'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result7',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('MAN_CITY', 'Man City'), ('TOTTENHAM', 'Tottenham'), ('DRAW', 'Draw')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result8',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('WEST_HAM', 'West Ham'), ('LEICESTER_CITY', 'Leicester City'), ('DRAW', 'Draw')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result9',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('YANKEES', 'Yankees'), ('ROYALS', 'Royals')], max_length=10, null=True),
        ),
    ]
