# Generated by Django 2.2 on 2019-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20190412_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game1',
            field=models.CharField(blank=True, choices=[('', 'Low thru Fri'), ('PLAYER_1', 'Jordan Speith'), ('PLAYER_2', 'Dustin Johnson'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game4',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('NUGGETS', 'Nuggets'), ('SPURS', 'Spurs')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game6',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ROYALS', 'Royals'), ('INDIANS', 'Indians'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result1',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('PLAYER_1', 'Jordan Speith'), ('PLAYER_2', 'Dustin Johnson'), ('TIED', 'Tied')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result6',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('ROYALS', 'Royals'), ('INDIANS', 'Indians'), ('TIED', 'Tied')], max_length=20, null=True),
        ),
    ]
