# Generated by Django 2.2 on 2019-04-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20190412_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardmodel',
            options={'ordering': ['total_points', 'player__HC']},
        ),
        migrations.AlterModelOptions(
            name='touragendamodel',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game1',
            field=models.CharField(blank=True, choices=[('', 'RBC low thru Fri'), ('PLAYER_1', 'Jordan Spieth'), ('PLAYER_2', 'Dustin Johnson'), ('TIED', 'Tied')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result1',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('PLAYER_1', 'Jordan Spieth'), ('PLAYER_2', 'Dustin Johnson'), ('TIED', 'Tied')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TopGolfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='reference', max_length=20, null=True)),
                ('fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifthTopGolf', to='catalog.PlayerModel')),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstTopGolf', to='catalog.PlayerModel')),
                ('fourth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthTopGolf', to='catalog.PlayerModel')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondTopGolf', to='catalog.PlayerModel')),
                ('sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixthTopGolf', to='catalog.PlayerModel')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdTopGolf', to='catalog.PlayerModel')),
            ],
        ),
        migrations.CreateModel(
            name='RacingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='reference', max_length=20, null=True)),
                ('fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifthRacing', to='catalog.PlayerModel')),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstRacing', to='catalog.PlayerModel')),
                ('fourth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthRacing', to='catalog.PlayerModel')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondRacing', to='catalog.PlayerModel')),
                ('sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixthRacing', to='catalog.PlayerModel')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdRacing', to='catalog.PlayerModel')),
            ],
        ),
    ]
