# Generated by Django 2.2 on 2019-04-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20190415_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='first',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='second',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='third',
        ),
        migrations.DeleteModel(
            name='RacingModel',
        ),
        migrations.DeleteModel(
            name='TopGolfModel',
        ),
    ]
