# Generated by Django 2.2 on 2019-04-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20190415_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGolfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='reference', max_length=20, null=True)),
                ('fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifthTopGolf', to='catalog.PlayerModel')),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstTopGolf', to='catalog.PlayerModel')),
                ('fourth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthTopGolf', to='catalog.PlayerModel')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondTopGolf', to='catalog.PlayerModel')),
                ('sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixthTopGolf', to='catalog.PlayerModel')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdTopGolf', to='catalog.PlayerModel')),
            ],
        ),
        migrations.CreateModel(
            name='RacingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='reference', max_length=20, null=True)),
                ('fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifthRacing', to='catalog.PlayerModel')),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstRacing', to='catalog.PlayerModel')),
                ('fourth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthRacing', to='catalog.PlayerModel')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondRacing', to='catalog.PlayerModel')),
                ('sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixthRacing', to='catalog.PlayerModel')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdRacing', to='catalog.PlayerModel')),
            ],
        ),
    ]
