# Generated by Django 2.2 on 2019-04-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_racingmodel_topgolfmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game1',
            field=models.CharField(blank=True, choices=[('', 'RBC low thru Fri'), ('PLAYER_1', 'Jordan Spieth'), ('PLAYER_2', 'Dustin Johnson'), ('TIED', 'Tied')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game10',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ISLANDERS', 'Islanders'), ('PENGUINS', 'Penguins')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game2',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('GIANTS', 'Giants'), ('PIRATES', 'Pirates')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game3',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('PACERS', 'Pacers'), ('CELTICS', 'Celtics')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game4',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('NUGGETS', 'Nuggets'), ('SPURS', 'Spurs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game5',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('MAPLE_LEAFS', 'Maple Leafs'), ('BRUINS', 'Bruins')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game6',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ROYALS', 'Royals'), ('INDIANS', 'Indians'), ('TIED', 'Tied')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game7',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('MAN_CITY', 'Man City'), ('TOTTENHAM', 'Tottenham'), ('DRAW', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game8',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('WEST_HAM', 'West Ham'), ('LEICESTER_CITY', 'Leicester City'), ('DRAW', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game9',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('YANKEES', 'Yankees'), ('KANSAS_CITY', 'Kansas City')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result9',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('YANKEES', 'Yankees'), ('KANSAS_CITY', 'Kansas City')], max_length=20, null=True),
        ),
    ]
