# Generated by Django 2.2 on 2019-04-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20190415_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rd1CTPModel',
        ),
    ]
