# Generated by Django 2.2 on 2019-04-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_rd3holemodel_rd3scoremodel_rd3slotmodel_rd3stablefordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd1slotmodel',
            name='tussle_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
