# Generated by Django 2.2 on 2019-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_rd1slotmodel_tussle_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd2slotmodel',
            name='tussle_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd3slotmodel',
            name='tussle_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
