# Generated by Django 2.2 on 2019-04-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_auto_20190417_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rd1slotmodel',
            options={'ordering': ['-player_rankscore', '-tussle_score', 'player_name__HC']},
        ),
        migrations.AlterModelOptions(
            name='rd2slotmodel',
            options={'ordering': ['-player_rankscore', '-tussle_score', 'player_name__HC']},
        ),
        migrations.AlterModelOptions(
            name='rd3slotmodel',
            options={'ordering': ['-player_rankscore', '-tussle_score', 'player_name__HC']},
        ),
    ]
