# Generated by Django 2.2 on 2019-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20190417_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game10',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('HURRICANES', 'Hurricanes'), ('CAPITALS', 'Capitals')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result10',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('HURRICANES', 'Hurricanes'), ('CAPITALS', 'Capitals')], max_length=20, null=True),
        ),
    ]
